"""Baseline schema.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-30

The repository had no migrations at all, so the SPEC-01 and SPEC-10 schema could not reach a
deployed database (`make dev` ran `alembic upgrade` as a no-op). This establishes the baseline.

It creates the schema from `Base.metadata` rather than from rendered DDL, deliberately:

* It is exact by construction. `JSONType` is `JSON` with a `JSONB` variant for PostgreSQL, and the
  dedupe index in SPEC-10 F4 is a partial unique index with dialect-specific predicates. Rendered
  DDL autogenerated against SQLite would silently lose both, and there is no PostgreSQL available in
  this environment to autogenerate against correctly.
* Nothing is deployed yet, so there is no existing database this must reproduce byte for byte.

Later revisions should be ordinary autogenerated DDL against real PostgreSQL; autogenerate diffs
metadata against the live database and is unaffected by how this baseline was applied.
"""

from __future__ import annotations

from alembic import op

from bidtriage.core.models import Base

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
