"""SPEC-02: extraction retry bookkeeping and the geocode cache.

Revision ID: 0002_spec02_extraction
Revises: 0001_baseline
Create Date: 2026-09-30

`raw_messages` gains the two columns SPEC-02 F3 needs to tell "retrying" from "gave up": how many
attempts a message has had and why the last one failed. `geocode_cache` keeps the geocoding
provider out of the hot path for a job site already seen.

Every step is guarded by an inspection of the live database, because `0001_baseline` builds the
schema from `Base.metadata` rather than from frozen DDL (see its docstring for why). On a database
created after this change the baseline already contains both, and this revision is a no-op that
only moves the version stamp; on one created before it, it applies the delta. Once a real
PostgreSQL deployment exists, the baseline should be frozen as rendered DDL and later revisions can
go back to being plain autogenerated `op` calls.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0002_spec02_extraction"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def _inspector() -> sa.Inspector:
    return sa.inspect(op.get_bind())


def _columns(table: str) -> set[str]:
    return {c["name"] for c in _inspector().get_columns(table)}


def _indexes(table: str) -> set[str]:
    return {i["name"] for i in _inspector().get_indexes(table)}


def upgrade() -> None:
    existing = _columns("raw_messages")
    if "extraction_attempts" not in existing:
        op.add_column(
            "raw_messages",
            sa.Column("extraction_attempts", sa.Integer(), nullable=False, server_default="0"),
        )
    if "extraction_error" not in existing:
        op.add_column("raw_messages", sa.Column("extraction_error", sa.String(length=400)))
    if "ix_raw_messages_extraction_status" not in _indexes("raw_messages"):
        op.create_index("ix_raw_messages_extraction_status", "raw_messages", ["extraction_status"])
    if "geocode_cache" not in _inspector().get_table_names():
        op.create_table(
            "geocode_cache",
            sa.Column("query_key", sa.String(length=64), primary_key=True),
            sa.Column("query", sa.String(length=400), nullable=False),
            sa.Column("lat", sa.Float(), nullable=False),
            sa.Column("lon", sa.Float(), nullable=False),
            sa.Column("precision", sa.String(length=10), nullable=False, server_default="none"),
        )


def downgrade() -> None:
    if "geocode_cache" in _inspector().get_table_names():
        op.drop_table("geocode_cache")
    if "ix_raw_messages_extraction_status" in _indexes("raw_messages"):
        op.drop_index("ix_raw_messages_extraction_status", table_name="raw_messages")
    existing = _columns("raw_messages")
    if "extraction_error" in existing:
        op.drop_column("raw_messages", "extraction_error")
    if "extraction_attempts" in existing:
        op.drop_column("raw_messages", "extraction_attempts")
